import React, { useEffect, useState } from 'react';

interface IranStockWidgetProps {
  tsetmcId?: string;
  symbol?: string;
}

const IranStockWidget: React.FC<IranStockWidgetProps> = ({ tsetmcId, symbol }) => {
  const [timestamp, setTimestamp] = useState(Date.now());

  // Auto-refresh the image every 60 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      setTimestamp(Date.now());
    }, 60000);
    return () => clearInterval(interval);
  }, []);

  if (!tsetmcId) {
    return (
      <div className="w-full h-full flex flex-col items-center justify-center bg-gray-50 text-gray-400 p-4 text-center">
        <span className="text-3xl mb-2">📉</span>
        <span className="text-sm">شناسه TSETMC یافت نشد.</span>
      </div>
    );
  }

  // TSETMC Chart Image URL (Returns a static PNG generated by their server)
  // t=0 implies daily/intraday
  const chartUrl = `http://www.tsetmc.com/tsev2/chart/plot.aspx?i=${tsetmcId}&t=0&_=${timestamp}`;
  
  // External Link Construction
  const sahamyabUrl = symbol ? `https://www.sahamyab.com/stock/${symbol}` : '#';
  const tsetmcPageUrl = `http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=${tsetmcId}`;

  return (
    <div className="w-full h-full bg-white relative group overflow-hidden flex flex-col">
      {/* Chart Image Container */}
      <div className="flex-grow relative flex items-center justify-center bg-white p-2">
        <img 
          src={chartUrl} 
          alt={`${symbol} chart`} 
          className="max-w-full max-h-full object-contain pointer-events-none opacity-90 transition-opacity duration-300 group-hover:opacity-100"
          loading="lazy"
          onError={(e) => {
             e.currentTarget.style.display = 'none';
          }}
        />
        
        {/* Helper Text */}
        <div className="absolute top-2 right-2 bg-gray-100/80 px-2 py-0.5 rounded text-[10px] text-gray-500 backdrop-blur-sm">
           منبع: TSETMC (با تاخیر)
        </div>
      </div>

      {/* Overlay Action Button */}
      <div className="absolute inset-0 bg-black/5 opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-center justify-center pointer-events-none">
          <div className="pointer-events-auto flex flex-col gap-2">
             <a 
               href={tsetmcPageUrl} 
               target="_blank" 
               rel="noopener noreferrer"
               className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium shadow-lg hover:bg-blue-700 transition-colors transform hover:scale-105 flex items-center gap-2"
             >
               <span>🔍</span> مشاهده در TSETMC
             </a>
             {symbol && (
                 <a 
                   href={sahamyabUrl} 
                   target="_blank" 
                   rel="noopener noreferrer"
                   className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm font-medium shadow-lg hover:bg-green-700 transition-colors transform hover:scale-105 flex items-center gap-2"
                 >
                   <span>📈</span> تحلیل در سهام‌یاب
                 </a>
             )}
          </div>
      </div>
    </div>
  );
};

export default IranStockWidget;